### PR TITLE
Wk05 HW

### PR DESCRIPTION
**Pull request by NMdluli**
hi Dr. D,

I am submitting my wk05 hw in the solutions folder. I wasn't sure where to submit it, I also have the notes in my projects folder. 

Thanks,
Nonto

### CODE REVIEW

**Comment by NMdluli** [comment]
moved solution notes to exercises/ Nvm35/ wk05

**Comment by JudoWill** [comment]
The stuff you have is right, there's just some extra files that you've committed.

From your root:
```bash
git rm -r content/wk05/solution/NMdluli
git commit -m 'removed extra files'
git push
```

Then it'll automagically appear here and I'll merge.

**Comment by NMdluli** [comment]
I just removed the extra files.

**Comment by JudoWill** [comment]
Perfect! Merging them in!

**Pull request merged**
