### PR TITLE
Updates through week 6/7

### PR DESCRIPTION
**Pull request by ardenedgerton**
I have been an idiot--and realzied that I was git pushing and syncing and pulling the changes that Dr. Dampier made without making the proper pull requests for this course. 

Included in this pull request is the following updates: 

Restructuring of my repos: 
repos/OMICS/projects/aoe23: 
- each week has a folder containing a readme with only my critical notes from class
- I had previously stored everything in a big markdown with all of my notes and compiled assignments from previous weeks. 
- I added a data_summary.md within this folder based on the assignment from week 05. I previously had this stored elsewhere and now it is somewhere that makes sense and my projects folder is much more clean.

repos/OMICS/exercises/
- added an aoe23 folder to submit my assignments in a place that Dr. Dampier can now see clearly 
- added clear and concise updates within the following folders: 
- repos/OMICS/exercises/aoe23/wk05: now has a properly formatted and legible readme with the code used to work through seqkit 
- repos/OMICS/exercises/aoe23/wk06: has been updated (however I am still working on this part)

Please accept my pull request and my lack of understanding that even though my fork is synced and I am pushing and pulling (I was only doing that to my origin) and now I will hopefully continue to submit correctly ! Thank you

### CODE REVIEW

**Comment by JudoWill** [comment]
You've got all the things but you still added some files that'll conflict with others.

Do a:
```bash
git rm content/wk05/sample1.fq
git rm content/wk05/sample1.fq.gz
git rm content/wk05/scratchAE.csv
git rm content/wk05/scratchAE.tsv
git rm projects/aoe23/.README.md.swp

git commit -m 'removing extra files'
git push
```

Then the changes will show up here.

**Comment by ardenedgerton** [comment]
removed extra files and updated the new commit with updates to exercises/wk06/aoe23/README.md 
Let me know if I should do another pull request now or wait until completely finished?

**Comment by ardenedgerton** [comment]
I am now finished with any updates to the work from the past 2 weeks and ready to officially submit pull request for week 06/7 homework!! Thank you !

**Comment by JudoWill** [comment]
Still got a `.swp` file. These are temporary 'autosave' files that `nano` uses as you write you files. You should be careful not include them during `git add`. Before you do `git commit` you should **always** do `git status` and then check that only the files you intended are there. You can use `git reset path/to/file` to unstage files before commiting  
```
git rm projects/aoe23/.README.md.swp
git status
git commit -m 'removed another swap file'
git push
```

**Comment by ardenedgerton** [comment]
image

**Comment by ardenedgerton** [comment]
hi Dr. Dampier--I had tried this command a couple times but I didn't realize that I was in the wrong place. I then went to repos/OMICS and did the command and should now be good to submit this pull request! Thank you!

**Pull request merged**
